ecomm/ecomm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('', include('toko.urls', namespace='toko')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/toko/urls.py
from django.urls import path
from . import views

app_name = 'toko'

urlpatterns = [
     path('', views.HomeListView.as_view(), name='home-produk-list'),
     path('product/<slug>/', views.ProductDetailView.as_view(), name='produk-detail'),
     path('checkout/', views.CheckoutView.as_view(), name='checkout'),
     path('add-to-cart/<slug>/', views.add_to_cart, name='add-to-cart'),
     path('remove_from_cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
     path('order-summary/', views.OrderSummaryView.as_view(), name='order-summary'),
     path('payment/<payment_method>', views.PaymentView.as_view(), name='payment'),
     path('paypal-return/', views.paypal_return, name='paypal-return'),
     path('paypal-cancel/', views.paypal_cancel, name='paypal-cancel'),
     path('contact-us', views.ContactUsView.as_view(), name='contact-us'),
]

ecomm/toko/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

PILIHAN_KATEGORI = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

PILIHAN_LABEL = (
    ('NEW', 'primary'),
    ('SALE', 'info'),
    ('BEST', 'danger'),
)

PILIHAN_PEMBAYARAN = (
    ('P', 'Paypal'),
    ('S', 'Stripe'),
)

User = get_user_model()

class ProdukItem(models.Model):
    nama_produk = models.CharField(max_length=100)
    harga = models.FloatField()
    harga_diskon = models.FloatField(blank=True, null=True)
    slug = models.SlugField(unique=True)
    deskripsi = models.TextField()
    gambar = models.ImageField(upload_to='product_pics')
    label = models.CharField(choices=PILIHAN_LABEL, max_length=4)
    kategori = models.CharField(choices=PILIHAN_KATEGORI, max_length=2)

    def __str__(self):
        return f"{self.nama_produk} - ${self.harga}"

    def get_absolute_url(self):
        return reverse("toko:produk-detail", kwargs={
            "slug": self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("toko:add-to-cart", kwargs={
            "slug": self.slug
            })
    
    def get_remove_from_cart_url(self):
        return reverse("toko:remove-from-cart", kwargs={
            "slug": self.slug
            })
    
class OrderProdukItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    produk_item = models.ForeignKey(ProdukItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.produk_item.nama_produk}"

    def get_total_harga_item(self):
        return self.quantity * self.produk_item.harga
    
    def get_total_harga_diskon_item(self):
        return self.quantity * self.produk_item.harga_diskon

    def get_total_hemat_item(self):
        return self.get_total_harga_item() - self.get_total_harga_diskon_item()
    
    def get_total_item_keseluruan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_harga_diskon_item()
        return self.get_total_harga_item()
    
    def get_total_hemat_keseluruhan(self):
        if self.produk_item.harga_diskon:
            return self.get_total_hemat_item()
        return 0


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    produk_items = models.ManyToManyField(OrderProdukItem)
    tanggal_mulai = models.DateTimeField(auto_now_add=True)
    tanggal_order = models.DateTimeField(blank=True, null=True)
    ordered = models.BooleanField(default=False)
    alamat_pengiriman = models.ForeignKey('AlamatPengiriman', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

     
    def get_total_harga_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_item_keseluruan()
        return total
    
    def get_total_hemat_order(self):
        total = 0
        for order_produk_item in self.produk_items.all():
            total += order_produk_item.get_total_hemat_keseluruhan()
        return total

class AlamatPengiriman(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    alamat_1 = models.CharField(max_length=100)
    alamat_2 = models.CharField(max_length=100)
    negara = models.CharField(max_length=100)
    kode_pos = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username} - {self.alamat_1}"

    class Meta:
        verbose_name_plural = 'AlamatPengiriman'

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)
    payment_option = models.CharField(choices=PILIHAN_PEMBAYARAN, max_length=1)
    charge_id = models.CharField(max_length=50)

    def __self__(self):
        return self.user.username
    
    def __str__(self):
        return f"{self.user.username} - {self.payment_option} - {self.amount}"
    
    class Meta:
        verbose_name_plural = 'Payment'

ecomm/ecomm/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>

    <title>e-commerce {% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
  
    <!-- MDB icon -->
    <link rel="icon" href="{% static 'img/mdb-favicon.ico' %}" type="image/x-icon" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
    />
    <!-- MDB -->
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
  </head>
  <body>
    
    {% include 'navbar.html' %}
 

    <div class="mt-5 pt-4">
      {% if messages %}
          {% for message in messages %}
          <div class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissable">
              <strong>{{ message }}</strong>
            </div>
          </div>
          {% endfor %}
      {% endif %}
    </div>

    {% block content %}
    {% endblock content %}
    
    {% include 'footer.html' %}
  
    {% include 'scripts.html' %}

    {% block scripts %}
    {% endblock scripts %}

  </body>
</html>

ecomm/ecomm/templates/carousel.html
<!-- carousel -->
<div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-mdb-ride="carousel">
    <div class="carousel-indicators">
        <button
                type="button"
                data-mdb-target="#carouselExampleCaptions"
                data-mdb-slide-to="0"
                class="active"
                aria-current="true"
                aria-label="Slide 1"
        ></button>
        <button
                type="button"
                data-mdb-target="#carouselExampleCaptions"
                data-mdb-slide-to="1"
                aria-label="Slide 2"
        ></button>
        <button
                type="button"
                data-mdb-target="#carouselExampleCaptions"
                data-mdb-slide-to="2"
                aria-label="Slide 3"
        ></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg" class="d-block w-100" alt="Wild Landscape"/>
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
            <div class="carousel-caption d-none d-sm-block mb-5">
                <h1 class="mb-4">
                    <strong>PRINCESS FASHION</strong>
                </h1>
                <p>
                    <strong>Temukan Gaya Anda dengan Kemudahan Belanja Online di Toko Kami - Fashion Berkualitas Tinggi Hanya di Sini!</strong>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg" class="d-block w-100" alt="Camera"/>
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
            <div class="carousel-caption d-none d-md-block mb-5">
                <h1 class="mb-4">
                    <strong>PRINCESS FASHION</strong>
                </h1>
                <p>
                    <strong>Temukan Gaya Anda dengan Kemudahan Belanja Online di Toko Kami - Fashion Berkualitas Tinggi Hanya di Sini!</strong>
                </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg" class="d-block w-100" alt="Exotic Fruits"/>
            <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
            <div class="carousel-caption d-none d-md-block mb-5">
                <h1 class="mb-4">
                    <strong>PRINCESS FASHION</strong>
                </h1>
                <p>
                    <strong>Temukan Gaya Anda dengan Kemudahan Belanja Online di Toko Kami - Fashion Berkualitas Tinggi Hanya di Sini!</strong>
                </p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

ecomm/ecomm/templates/contact_us.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}

<!--Main layout-->
<main>
    <div class="container">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #d1847d">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="#">Contact Us</a>

            </div>  
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section>
            <div class="text-center">
              <div class="row">
                
                <div class="col-lg-3 col-md-6 mb-4">
                 
                    <div class="card-body" >
                      <table >
                        <tr>
                            <td>Nama</td>
                            <td>:</td>
                            <td>
                                <input type="text" class="form-control rounded-0" placeholder="Nama Lengkap" aria-label="Nama Lengkap">
                            </td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>:</td>
                            <td>
                                <input type="email" class="form-control rounded-0" placeholder="Email" aria-label="Email">
                            </td>
                        </tr>
                        <tr>
                            <td>Pesan</td>
                            <td>:</td>
                            <td>
                                <textarea name="pesan" id="" cols="30" rows="10"  class="form-control rounded-0"></textarea>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3">
                                <input type="submit" name="" id="" value="Kirim" style="background-color: #d1847d; padding: 10 20;">
                            </td>
                        </tr>
                      </table>
                    </div>
                  </div>
                </div>

              </div>
            </div>
          </section>
        <!-- End Products -->

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item">
                  {% if page_obj.has_previous %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                  {% endif %}
                </li>
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                <li class="page-item">
                  {% if page_obj.has_next %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                  {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

ecomm/ecomm/templates/home.html
{% extends 'base.html' %}

{% block content %}

{% include 'carousel.html' %}

<!--Main layout-->
<main>
    <div class="container">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark mt-3 mb-5 shadow p-2" style="background-color: #d1847d">
            <!-- Container wrapper -->
            <div class="container-fluid">

                <!-- Navbar brand -->
                <a class="navbar-brand" href="#">Categories:</a>

                <!-- Toggle button -->
                <button
                        class="navbar-toggler"
                        type="button"
                        data-mdb-toggle="collapse"
                        data-mdb-target="#navbarSupportedContent2"
                        aria-controls="navbarSupportedContent2"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent2">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                        <!-- Link -->
                        <li class="nav-item acitve">
                            <a class="nav-link text-white" href="#">All</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Shirts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Sport wears</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="#">Outwears</a>
                        </li>

                    </ul>

                    <!-- Search -->
                    <form class="w-auto py-1" style="max-width: 12rem">
                        <input type="search" class="form-control rounded-0" placeholder="Search" aria-label="Search">
                    </form>

                </div>
            </div>
            <!-- Container wrapper -->
        </nav>
        <!-- Navbar -->

        <!-- Products -->
        <section>
            <div class="text-center">
              <div class="row">
                
                {% for pItem in object_list %}
                <div class="col-lg-3 col-md-6 mb-4">
                  <div class="card" style="background-color: #d1847d4f;">
                    <div class="bg-image hover-zoom ripple ripple-surface ripple-surface-light"
                      data-mdb-ripple-color="light">
                      <img src="{{ pItem.gambar.url }}"
                        class="w-100" />
                      <a href="{{ pItem.get_absolute_url }}"> 
                        <div class="mask">
                          <div class="d-flex justify-content-start align-items-end h-100">
                            <h5><span class="badge bg-{{ pItem.get_label_display }} ms-2">{{ pItem.label }}</span></h5>
                          </div>
                        </div>
                        <div class="hover-overlay">
                          <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                        </div>
                      </a>
                    </div>
                    <div class="card-body">
                      <a href="{{ pItem.get_absolute_url }}" class="text-reset">
                        <h5 class="card-title mb-2">{{ pItem.nama_produk }}</h5>
                      </a>
                      <a href="" class="text-reset ">
                        <p>{{ pItem.get_kategori_display }}</p>
                      </a>
                      <h6 class="mb-3 price">${% if pItem.harga_diskon %}{{ pItem.harga_diskon }}{% else %}{{ pItem.harga }}{% endif %}</h6>
                    </div>
                  </div>
                </div>
                {% empty %}
                  <p>Data Produk belum tersedia</p>
                {% endfor %}

              </div>
            </div>
          </section>
        <!-- End Products -->

        <!-- Pagination -->
        {% if is_paginated %}
        <nav aria-label="Page navigation example" class="d-flex justify-content-center mt-3">
            <ul class="pagination">
                <li class="page-item">
                  {% if page_obj.has_previous %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                  {% endif %}
                </li>
                <li class="page-item active"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
                <li class="page-item">
                  {% if page_obj.has_next %}
                    <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                  {% endif %}
                </li>
            </ul>
        </nav>
        {% endif %}
        <!-- Pagination -->
    </div>
</main>
<!--Main layout-->
{% endblock content %}

ecomm/ecomm/templates/navbar.html
{% load cart_template_tags %}

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-white">
    <!-- Container wrapper -->
    <div class="container">    
        <!-- Toggle button -->
        <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent1"
        aria-controls="navbarSupportedContent1"
        aria-expanded="false"
        aria-label="Toggle navigation"
        >
        <i class="fas fa-bars"></i>
        </button>
    
        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent1">      
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-sm-0" href="#">
            <img
            src="/media/logo.png"
            height="20"
            alt="MDB Logo"
            loading="lazy"
            />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
            <a class="nav-link " href="/">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'toko:checkout' %}">Checkout</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'toko:contact-us' %}">Contact Us</a>
                </li>
        </ul>
        <!-- Left links -->      
        </div>
        <!-- Collapsible wrapper -->
        
        <!-- Right elements -->
        <div class="d-flex align-items-center">
            {% if request.user.is_authenticated %}
                <!-- Icon -->
                <a class="nav-link me-3" href="{% url 'toko:order-summary' %}">
                    <i class="fas fa-shopping-cart"></i>
                    <span class="badge rounded-pill badge-notification bg-danger">{{ request.user|total_produk_dikeranjang }}</span>
                </a>
                <a class="nav-link me-3" href="{% url 'account_logout' %}">Logout
                    <i class="fas fa-right-from-bracket"></i>
                </a>
            {% else %}
                <a class="nav-link me-3" href="{% url 'account_login' %}">Login
                <i class="fas fa-right-to-bracket"></i>
            {% endif %}
        </div> 
        <!-- Right elements -->
        
    </div>
    <!-- Container wrapper -->
</nav>
    <!-- Navbar -->

ecomm/ecomm/templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 mt-4 mb-4">
            <h1 class="text-center">Order Summary</h1>
        </div>
    </div>
    <table class="table align-middle mb-0 bg-white">
        <thead class="bg-light">
        <tr>
            <th>#</th>
            <th>Nama Produk</th>
            <th>Harga</th>
            <th>Quantity</th>
            <th>Total Harga</th>
        </tr>
        </thead>
        <tbody>
            {% for pItem in keranjang.produk_items.all %}
            <tr>
                <td scope="row">
                    {{ forloop.counter }}
                </td>
                <td>
                    <a href="{% url 'toko:produk-detail' pItem.produk_item.slug %}">
                        <div class="d-flex align-items-center">
                            <img
                                src="{{ pItem.produk_item.gambar.url }}"
                                alt=""
                                style="width: 45px; height: 45px"
                                class="rounded-circle"
                                />
                            <div class="ms-3">
                            <p class="fw-bold mb-1">{{ pItem.produk_item.nama_produk }}</p>
                            <p class="text-muted mb-0"> {{ pItem.produk_item.deskripsi|truncatewords:10 }}</p>
                            </div>
                        </div>
                    </a>
                </td>
                <td>
                    <div>$
                        {% if pItem.produk_item.harga_diskon %}
                        {{ pItem.produk_item.harga_diskon }}
                        {% else %}
                        {{ pItem.produk_item.harga }}
                        {% endif %}
                    </div>
                </td>
                <td>{{ pItem.quantity }}</td>
                <td>                
                    {% if pItem.produk_item.harga_diskon %}
                    ${{ pItem.get_total_harga_diskon_item }}
                    <span class="badge badge-danger rounded-pill d-inline">Hemat ${{ pItem.get_total_hemat_item }}</span>
                    {% else %}
                    ${{ pItem.get_total_harga_item }}
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='5'>Keranjang kosong</td>
            </tr>
            <tr>
                <td colspan="5">
                <a class="btn btn-primary float-end" href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endfor %}

            {% if keranjang.get_total_harga_order %}
            <tr>
                <td colspan="4"><b>Total Belanja</b></td>
                <td><b>${{ keranjang.get_total_harga_order }}</b>
                    {% if keranjang.get_total_hemat_order %}
                    <span class="badge badge-danger">Hemat ${{ keranjang.get_total_hemat_order }}</span>
                    {% endif %}
                </td>
            </tr>

            <tr>
                <td colspan="5">
                <a class='btn btn-info float-end ml-2' href="{% url 'toko:checkout' %}">Checkout</a>
                <a class='btn btn-danger' href="{% url 'toko:home-produk-list' %}">Lanjut belanja</a>
                </td>
            </tr>
            {% endif %}
        </tbody>
  </table>
</div>
{% endblock content %}

ecomm/ecomm/templates/payment.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="d-flex justify-content-center">
    <div class="row justify-content-center">
      <div class="col pt-5 pb-5">
        <p>Total belanjaan kamu : <strong>${{ order.get_total_harga_order }}</strong></p>
        <br />
        {% if is_paypal %}
        <div>{{ paypalform.render }}</div>
        {% else %}
        <div>Pembayaran Strip belum diaktifkan gunakan Paypal</div>
        <a href="{% url 'toko:payment' 'paypal' %}"><div class="btn btn-info">Paypal</div></a>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock content %}

ecomm/ecomm/templates/product_detail.html
{% extends 'base.html' %}

{% block content%}

<!--Main layout-->
<main class="mt-5 pt-4">
    <div class="container mt-5">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <img src="{{ object.gambar.url }}" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">
                <!--Content-->
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                            <span class="badge bg-dark me-1">{{ object.get_kategori_display }}</span>
                        </a>
                        {% if object.label == 'NEW' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">New</span>
                        </a>
                        {% elif object.label == 'SALE' %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Sale</span>
                        </a>
                        {% else %}
                        <a href="">
                            <span class="badge bg-{{ object.get_label_display }} me-1">Bestseller</span>
                        </a>
                        {% endif %}
                    </div>

                    <p class="lead">
                        {% if object.harga_diskon %}
                        <span class="me-1">
                            <del>${{ object.harga }}</del>
                        </span>
                        <span>${{ object.harga_diskon }}</span>
                        {% else %}
                        <span>${{ object.harga }}</span>
                        {% endif %}
                    </p>

                    <strong><p style="font-size: 20px;">Deskripsi</p></strong>

                    <p>{{ object.deskripsi }}</p>
                    <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary ms-1">
                        Tambah ke keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger ms-1" >
                        Kurangi keranjang
                        <i class="fas fa-shopping-cart ms-1"></i>
                    </a>
                </div>
                <!--Content-->
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <hr />

        <!--Grid row-->
        <div class="row d-flex justify-content-center" style="background-color: #8b626050;">
            <!--Grid column-->
            <div class="col-md-6 text-center">
                <h4 class="my-4 h4">Additional information</h4>

                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates, quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->

        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="" />
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
</main>
<!--Main layout-->
{% endblock content%}

ecomm/ecomm/templates/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>